### ISSUE TITLE
Error at io.github.pseudoresonance.pixy2api.Pixy2Line.getFeatures(Pixy2Line.java:147): Unhandled exception: java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 6

### ISSUE THREAD

**Issue by Ernie3** [PseudoResonance/Pixy2JavaAPI#6]
This happens when there is an intersection. I think the issue is with the above for loop being for i "<=" instead of just "<". I will submit the merge request shortly to fix this if you wish to take a look. Btw, thank you for this API. It has saved us a ton of time this past build season!

**Comment by Ernie3** [comment]
Full stack trace (code is a private repo, if you wish to see the code we were using I can make public and/or send it): 
Unhandled exception: java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 6
Error at io.github.pseudoresonance.pixy2api.Pixy2Line.getFeatures(Pixy2Line.java:147): Unhandled exception: java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 6
at io.github.pseudoresonance.pixy2api.Pixy2Line.getFeatures(Pixy2Line.java:147)
at io.github.pseudoresonance.pixy2api.Pixy2Line.getAllFeatures(Pixy2Line.java:87)
at frc.robot.vision.PixyCam.getLines(PixyCam.java:30)
at frc.robot.Robot.disabledPeriodic(Robot.java:114)
at edu.wpi.first.wpilibj.IterativeRobotBase.loopFunc(IterativeRobotBase.java:212)
at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:81)
at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:263)
at frc.robot.Main.main(Main.java:27)
Robots should not quit, but yours did!
Warning at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:274): Robots should not quit, but yours did!

**Comment by Ernie3** [comment]
I should mention, we were using v1.3.1

**Comment by PseudoResonance** [comment]
Looks good, thanks for the help! And I've just been upping the version number with any bug change immediately as it's gotten so close to the competitions in the hope that any issues would be fixed and everyone using it would have the fixes well before they need to compete.
